config/routes.rb
Rails.application.routes.draw do
  root to: "foods#index"
  resources :foods, except: :index do
  collection do
      get 'newprofile'
      get 'indexprofile'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, :unit, :death, :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @foods = Food.all
  end

  def indexprofile
    @foods = Food.all
  end
  
  def new
    @food = Food.new
  end
  
  def newprofile
  end

  def create
    Food.create(food_params)
    redirect_to root_path
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    food = Food.find(params[:id])
    food.update(food_params)
    redirect_to food_path(food.id)
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to root_path
  end

  private
  def food_params
    params.require(:food).permit(:name, :unit, :death, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap&subset=japanese" rel="stylesheet">
</head>

<body class="emojitachi">
  <%# <%= link_to "　",  editprofile_foods_path , class: "edittorisetsu" %>
  <div clas="moji">
    <div class="moji__tsu"></div>
    <div class="moji__ku"></div>
    <div class="moji__ri"></div>
    <div class="moji__na"></div>
    <div class="moji__o"></div>
    <div class="moji__so"></div>
    <div class="moji__u"></div>
  </div>

  <div class="ctt_title">
  </div>

  <%= form_with model: @food, class: :eform, local: true do |form| %>
    <div class="eform__name-icon"></div>
    <%= form.text_field :name, placeholder: :なんてもの, class: :eform__name %>
    <div class="eform__unit-icon"></div>
    <%= form.text_field :unit, placeholder: :単位, class: :eform__unit %>
    <div class="eform__death-icon"></div>
    <%= form.number_field :death, placeholder: :致死量, class: :eform__death %>
    <div class="eform__description-icon"></div>
    <%= form.text_area :description, placeholder: :説明, class: :eform__description %>
    <div class="eform__btn-icon"></div>
    <%= form.submit '　', class: :eform__btn %>
  <% end %>
  <div class="sougen">
    <footer class="sougen__ber"></footer>
  </div>



  <div class="content">
      <a class="js-modal-open" href="">　</a>
  </div>
  <div class="modal js-modal">
      <div class="modal__wrap js-modal-close"></div>
      <div class="modal__bg js-modal-close">
        <div class="modal__bg--editBee">
        ハチさんの顔を押すとホームに戻れるよ！
        </div>
        <div class="modal__bg--editTanpopo">
        タンポポのタネを押すと『ちしりょう』を作れるよ！
        </div>
        <div class="modal__bg--editEdit">
        作った人に『けいい』<br>をはらって作りなおしてね！<br><br>
        文字や数字を触ると<br>編集ができるよ！
        </div>
        <div class="modal__bg--editOk">
        作りなおしたら落とし穴を押してね！
        </div>
      </div>
      </div><!--modal__inner-->
  </div><!--modal-->


<script type="text/javascript">
$(function(){
  $('.js-modal-open').on('click',function(){
      $('.js-modal').fadeIn();
      return false;
  });
  $('.js-modal-close').on('click',function(){
      $('.js-modal').fadeOut();
      return false;
  });
});
</script>

</body>

app/views/foods/index.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap&subset=japanese" rel="stylesheet">
</head>

<body class="indexbody">
  <%# <%= link_to "　", indexprofile_foods_path, class: "indexprofile" %>

  <% @foods.each do |food| %>
        <div class="foods">
          <%= link_to food.name, food_path(food.id), class: "foods__list" %>
        </div>
  <% end %>
</body>



  <div class="content">
      <a class="js-modal-open" href="">　</a>
  </div>
  <div class="modal js-modal">
      <div class="modal__wrap js-modal-close"></div>
      <div class="modal__bg js-modal-close">
        <div class="modal__bg--indexBee">
        ハチさんの顔を押すとホームに戻れるよ！
        </div>
        <div class="modal__bg--indexTanpopo">
        タンポポのタネを押すと『ちしりょう』を作れるよ！
        </div>
        <div class="modal__bg--indexKanban">
        見たい『ちしりょう』を押してね！
        </div>
        <div class="modal__bg--indexSetsu">
        『ちしりょう』を作って<br>　　　　　　看板を増やそう！
        </div>
      </div>
      </div><!--modal__inner-->
  </div><!--modal-->


<script type="text/javascript">
$(function(){
  $('.js-modal-open').on('click',function(){
      $('.js-modal').fadeIn();
      return false;
  });
  $('.js-modal-close').on('click',function(){
      $('.js-modal').fadeOut();
      return false;
  });
});
</script>

</body>

app/views/foods/indexprofile.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap&subset=japanese" rel="stylesheet">
</head>

<body class="indexbody">
  <%= link_to "　", root_path , class: "reindex" %>
  <div class="indexsiro">
    <div class="new-bee">
    ハチさんの顔を押すとホームに戻れるよ！
    </div>
    <div class="new-tanpopo">
    タンポポのタネを押すと『ちしりょう』を作れるよ！
    </div>
    <div class="index-kanban">
    見たい『ちしりょう』を押してね！
    </div>
    <div class="index-setsu">
    『ちしりょう』を作って<br>　　　　　　看板を増やそう！
    </div>
  </div>
  <% @foods.each do |food| %>
        <div class="foods">
          <%= link_to food.name, food_path(food.id), class: "foods__list" %>
        </div>
  <% end %>
</body>

app/views/foods/new.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap&subset=japanese" rel="stylesheet">
</head>

<body class="mojitachi">
  <div clas="moji">
    <div class="moji__tsu"></div>
    <div class="moji__ku"></div>
    <div class="moji__kotsu"></div>
    <div class="moji__te"></div>
    <div class="moji__mi"></div>
    <div class="moji__yo"></div>
    <div class="moji__u"></div>
  </div>

  <%# <%= link_to "　", newprofile_foods_path , class: "torisetsu" %>

  <%= form_with model: @food, class: :form, local: true do |form| %>
    <label>
    <div class="form__name-icon"></div>
    <%= form.text_field :name, class: :form__name %>
    <div class="form__unit-icon"></div>
    <%= form.number_field :death, class: :form__death %>
    <div class="form__death-icon"></div>
    <%= form.text_field :unit, class: :form__unit %>
    <div class="form__description-icon"></div>
    <%= form.text_area :description, class: :form__description %>
    <div class="form__btn-icon"></div>
    <%= form.submit '　　　', class: :form__btn %>
  <% end %>
  <div class="sougen">
    <footer class="sougen__ber"></footer>
  </div>
</body>



  <div class="content">
      <a class="js-modal-open" href="">　</a>
  </div>
  <div class="modal js-modal">
      <div class="modal__wrap js-modal-close"></div>
      <div class="modal__bg js-modal-close">
        <div class="modal__bg--newBee">
        ハチさんの顔を押すとホームに戻れるよ！
        </div>
        <div class="modal__bg--newTanpopo">
        タンポポのタネを押すと『ちしりょう』を作れるよ！
        </div>
        <div class="modal__bg--newKi">
        きりかぶを押して『たべもの』や<br>『のみのも』の名前を入れてね！
        </div>
        <div class="modal__bg--newKuma">
        クマさんの体を押して<br>『ちしりょう』を入れてね！<br>
        半角数字の4桁までで入れてね！
        </div>
        <div class="modal__bg--newHamu">
        ハムスターさんのおなか<br>を押してちしりょうの<br>『たんい』を入れてね！
        </div>
        <div class="modal__bg--newKusa">
        このへんの草を押して<br>　『せつめい』を書いてね！
        </div>
        <div class="modal__bg--newMizu">
        全部入れ終わったら<br>水たまりを押してね！
        </div>
      </div>
      </div><!--modal__inner-->
  </div><!--modal-->


<script type="text/javascript">
$(function(){
  $('.js-modal-open').on('click',function(){
      $('.js-modal').fadeIn();
      return false;
  });
  $('.js-modal-close').on('click',function(){
      $('.js-modal').fadeOut();
      return false;
  });
});
</script>

</body>

app/views/foods/newprofile.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap&subset=japanese" rel="stylesheet">
</head>

<body class="mojitachi">
  <div class="moji">
    <div class="moji__tsu"></div>
    <div class="moji__ku"></div>
    <div class="moji__kotsu"></div>
    <div class="moji__te"></div>
    <div class="moji__mi"></div>
    <div class="moji__yo"></div>
    <div class="moji__u"></div>
  </div>

  <%= link_to "　", new_food_path , class: "retorisetsu" %>

  <div class="newsiro">
    <div class="new-bee">
    ハチさんの顔を押すとホームに戻れるよ！
    </div>
    <div class="new-tanpopo">
    タンポポのタネを押すと『ちしりょう』を作れるよ！
    </div>
    <div class="new-ki">
    きりかぶを押して『たべもの』や<br>『のみのも』の名前を入れてね！
    </div>
    <div class="new-kuma">
    クマさんの体を押して<br>『ちしりょう』を入れてね！<br>
    半角数字の4桁までで入れてね！
    </div>
    <div class="new-hamu">
    ハムスターさんのおなか<br>を押してちしりょうの<br>『たんい』を入れてね！
    </div>
    <div class="new-kusa">
    このへんの草を押して<br>　『せつめい』を書いてね！
    </div>
    <div class="new-mizu">
    全部入れ終わったら<br>水たまりを押してね！
    </div>
  </div>

  <%= form_with model: @food, class: :form, local: true do |form| %>
    <label>
    <%# <%= form.radio_button :mvfd, "にく" にく </label> %>
    <%# <label><%= form.radio_button :mvfd, "やさい" やさい</label> %>
    <%# <label><%= form.radio_button :mvfd, "さかな" さかな</label> %>
    <%# <label><%= form.radio_button :mvfd, "のみもの" のみもの</label> %>
    <div class="form__name-icon"></div>
    <%= form.text_field :name, class: :form__name %>
    <div class="form__unit-icon"></div>
    <%= form.number_field :death, class: :form__death %>
    <div class="form__death-icon"></div>
    <%= form.text_field :unit, class: :form__unit %>
    <div class="form__description-icon"></div>
    <%= form.text_area :description, class: :form__description %>
    <div class="form__btn-icon"></div>
    <%= form.submit '', class: :form__btn %>
  <% end %>
  <div class="sougen">
    <footer class="sougen__ber"></footer>
  </div>
</body>

app/views/foods/profile.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap&subset=japanese" rel="stylesheet">
</head>

<body class="mojitachi">
  <div class="moji">
    <div class="moji__tsu"></div>
    <div class="moji__ku"></div>
    <div class="moji__kotsu"></div>
    <div class="moji__te"></div>
    <div class="moji__mi"></div>
    <div class="moji__yo"></div>
    <div class="moji__u"></div>
  </div>

  <%= link_to "　", new_food_path , class: "retorisetsu" %>

  <div class="siro">
    <div class="new-bee">
    ハチさんの顔を押すとホームに戻れるよ！
    </div>
    <div class="new-tanpopo">
    タンポポのタネを押すと『ちしりょう』を作れるよ！
    </div>
    <div class="new-ki">
    きりかぶを押して『たべもの』や<br>『のみのも』の名前を入れてね！
    </div>
    <div class="new-kuma">
    クマさんの体を押して<br>『ちしりょう』を入れてね！
    </div>
    <div class="new-hamu">
    ハムスターさんのおなか<br>を押してちしりょうの<br>『たんい』を入れてね！
    </div>
    <div class="new-kusa">
    このへんの草を押して<br>　『せつめい』を書いてね！
    </div>
    <div class="new-mizu">
    全部入れ終わったら<br>水たまりを押してね！
    </div>
  </div>

  <%= form_with model: @food, class: :form, local: true do |form| %>
    <label>
    <%# <%= form.radio_button :mvfd, "にく" にく </label> %>
    <%# <label><%= form.radio_button :mvfd, "やさい" やさい</label> %>
    <%# <label><%= form.radio_button :mvfd, "さかな" さかな</label> %>
    <%# <label><%= form.radio_button :mvfd, "のみもの" のみもの</label> %>
    <div class="form__name-icon"></div>
    <%= form.text_field :name, class: :form__name %>
    <div class="form__unit-icon"></div>
    <%= form.number_field :death, class: :form__death %>
    <div class="form__death-icon"></div>
    <%= form.text_field :unit, class: :form__unit %>
    <div class="form__description-icon"></div>
    <%= form.text_area :description, class: :form__description %>
    <div class="form__btn-icon"></div>
    <%= form.submit '', class: :form__btn %>
  <% end %>
  <div class="sougen">
    <footer class="sougen__ber"></footer>
  </div>
</body>

app/views/foods/show.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap&subset=japanese" rel="stylesheet">
</head>

<body class="showBody">
  <div class="showBody__name">
    <%= @food.name %>
  </div>
  <div class="showBody__death">
    <div class="showBody__death__num">
      <%= @food.death %>
    </div>
    <div class="showBody__death__unit">
      <%= @food.unit %>
    </div>
  </div>
  <div class="showBody__description">
    <%= simple_format @food.description %>
  </div>
  <div class="showBody__manage">
    <div  class="showBody__manage__editIcon"></div>
    <%= link_to "　", edit_food_path(@food.id), class: "showBody__manage__edit" %>
    <div  class="showBody__manage__deleteIcon"></div>
  </div>
</body>





  <div class="content">
      <a id="showtori" class="js-modal-open" href="" data-target="modal01">　</a>
  </div>
  <div id="modal01" class="modal js-modal">
      <div class="modal__wrap js-modal-close"></div>
      <div class="modal__bg js-modal-close">
        <div class="modal__bg--showBee">
        ハチさんの顔を押すとホームに戻れるよ！
        </div>
        <div class="modal__bg--showTanpopo">
        タンポポのタネを押すと『ちしりょう』を作れるよ！
        </div>
        <div class="modal__bg--showKumo">
        神様の乗ってる雲を押すと『へんしゅう』できるよ！
        </div>
        <div class="modal__bg--showHoshi">
        黄色い星を押すと記事が消えちゃうよ！
        </div>
      </div>
        </div><!--modal__inner-->
    </div><!--modal-->


    <button id="modal-open-btn">　</button>
        <%= link_to "　", food_path(@food.id), method: :delete, id: 'item-delete-btn' %>
<div id="overlay">
  <div id="modalWindow">
    <div class='kesanai-kanban'></div>
    <button id="modal-close-btn">やっぱり<br>消さない！</button>
    <div class='kesu-kanban'></div>
    <button id="delete-comformation-btn">消す</button>
  </div>
</div>

</body>


<script type="text/javascript">
$(function(){
    $('.js-modal-open').on('click',function(){
        $('.js-modal').fadeIn();
        return false;
    });
    $('.js-modal-close').on('click',function(){
        $('.js-modal').fadeOut();
        return false;
    });
});

document.addEventListener(
  "DOMContentLoaded", e => {
    let modal_open = document.getElementById("modal-open-btn");
    modal_open.onclick = function () {
      $('#overlay').fadeIn();
      document.getElementById('modal-close-btn').onclick = function () {
        $('#overlay').fadeOut();
      };
      document.getElementById("delete-comformation-btn").onclick = function () {
        document.getElementById("item-delete-btn").click();
      };
    };
  },
  false
);

</script>

</body>

app/views/layouts/application.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('favicon.ico') %>
    <title>FoodOfDeath</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header__home">
      <%= link_to "　", root_path , class: "header__title" %>
      <div class="header__create">
      <%= link_to "　", new_food_path, class: "header__edit" %>
      <div class="header__torisetsu">
    </header>
    <div>
      <%= yield %>
    </div>
  </body>
</html>